version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: MovieFlix
    environment:
      POSTGRES_DB: movieflix
      POSTGRES_USER: ${DATABASE_USERNAME_POSTGRESQL}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD_POSTGRESQL}
    ports:
      - "5432:5432"
    restart: always
