services:
  postgres:
    image: postgres:latest
    container_name: MovieFlix
    environment:
      POSTGRES_DB: movieflix
      POSTGRES_USER: ${DATABASE_USERNAME_POSTGRESQL}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD_POSTGRESQL}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - movieflix_data:/var/lib/postgresql/data

volumes:
  movieflix_data:

